-- GENERATED BY templates/nil.colortemplate. DON'T EDIT IT.
local colors = {
    bg = '#4c566a',
    yellow = '#ebcb8b',
    cyan = '#8fbcbb',
    green = '#a3be8c',
    orange = '#d08770',
    purple = '#b48ead',
    magenta = '#b48ead',
    grey = '#d8dee9',
    blue = '#81a1c1',
    vivid_blue = '#5e81ac',
    red = '#bf616a',
    error_red = '#bf616a',
    info_yellow = '#ebcb8b'
}

return colors
