local opt = vim.opt

opt.autoread = true
opt.background = 'dark'
opt.clipboard = 'unnamed'
opt.cmdheight = 1
opt.concealcursor = 'n'
opt.conceallevel = 0
opt.cursorline = true
opt.expandtab = true
opt.fillchars = 'vert:│,fold:-,eob: '
opt.foldcolumn = '0'
opt.foldexpr = 'nvim_treesitter#foldexpr()'
opt.foldlevelstart = 99
opt.foldmethod = 'expr'
opt.formatoptions = 'cqmMB'
opt.guifont = 'Hack_Nerd_Font_Mono:h14'
opt.hidden = true
opt.history = 500
opt.ignorecase = true
opt.linebreak = true
opt.list = true
opt.listchars = 'tab:· ,trail:-,nbsp:+'
opt.backup = false
opt.errorbells = false
opt.showmode = false
opt.visualbell = false
opt.wrap = false
opt.writebackup = false
opt.number = true
opt.path = vim.o.path .. '**'
opt.shiftwidth = 2
opt.shortmess = vim.o.shortmess .. 'I'
opt.showtabline = 1
opt.signcolumn = 'yes'
opt.smartcase = true
opt.softtabstop = 2
opt.spelllang = 'en_us,cjk'
opt.splitbelow = true
opt.splitright = true
opt.synmaxcol = 500
opt.tabstop = 2
opt.termguicolors = true
opt.updatetime = 100
opt.wildignore = vim.o.wildignore .. 'node_modules/**'
opt.completeopt = 'menu,menuone,noselect'
