require('plugins.loader').load()

require('plugins.config.dap')
require('plugins.config.zenmode')
require('plugins.config.rest')
require('plugins.config.gitsigns')
require('plugins.config.hop')
require('plugins.config.clipboard-image')
require('plugins.config.nvim-tree')
require('plugins.config.nvim-lspconfig')
require('plugins.config.nvim-cmp')
require('plugins.config.feline')
require('plugins.config.nvim-gps')
